# Generated by Django 6.0 on 2026-01-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
