# Generated by Django 6.0 on 2026-01-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='baths',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='guests',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
