# Generated by Django 6.0 on 2026-03-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_booking_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('cancelled', 'CANCELLED'), ('rejected', 'REJECTED')], default='pending', max_length=10),
        ),
    ]
