# Generated by Django 6.0 on 2026-06-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_propertymedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_link',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_state',
            field=models.CharField(choices=[('pending', 'PENDING'), ('requires_payment', 'REQUIRES_PAYMENT'), ('paid', 'PAID'), ('failed', 'FAILED')], default='pending', max_length=20),
        ),
    ]
