# Generated by Django 6.0 on 2026-06-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(choices=[('Banjul', 'Banjul'), ('Kololi', 'Kololi'), ('Kotu', 'Kotu'), ('Fajara', 'Fajara'), ('Brufut', 'Brufut'), ('Serekunda', 'Serekunda'), ('Bakau', 'Bakau'), ('Banjul West', 'Banjul West'), ('Banjul East', 'Banjul East'), ('Banjul North', 'Banjul North'), ('Banjul South', 'Banjul South'), ('Brikama', 'Brikama'), ('Janjanbureh', 'Janjanbureh'), ('Kanifing', 'Kanifing'), ('Kerewan', 'Kerewan'), ('Kuntaur', 'Kuntaur'), ('Mansakonko', 'Mansakonko'), ('Sukuta', 'Sukuta'), ('Yundum', 'Yundum')], max_length=100),
        ),
    ]
